#!/usr/bin/env python3
"""make_luts.py — emit the measured shaper curves as a C header.

The shapers are stored as MEASURED tables rather than fitted formulas because
that is what the measurements support:
  * med, hard and Crunch each reduce to one fixed shaper plus a pre-gain
    (§37, residuals 0.0008-0.07), so a single curve per family would do — but a
    per-setting table costs little and removes the fit residual entirely.
  * `soft` FOLDS and its per-bin width runs 0.25-0.75 (§35, §39), so it is not a
    static function at all. A sine-folder fit gave rms 0.07-0.13 with unstable
    parameters. A per-setting table is an honest approximation of a stage whose
    exact topology is not yet known, and the width is recorded alongside so the
    approximation is visible rather than implied.

Curves are odd-symmetric by measurement (§22: evens 18-20 dB below odds), so only
the positive half is stored.

Usage: tools/make_luts.py > src/shapers.h
"""
import os, sys
import numpy as np
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from segments import seg
from analyse import read_wav, resolve_probe

N = 129                      # samples over input 0..1
LAG_LO, LAG_HI = 150, 240    # under one period at 100 Hz (§32) — enforced, not remembered

FAMILIES = {
    'soft':   ('rig/renders/campaign2', 'rig/sets/campaign2 Project', 'sw100',
               [(0.0, '01_neutral'), (0.25, '05_soft_0.25'), (0.5, '06_soft_0.5'),
                (0.625, '07_soft_0.625'), (0.75, '08_soft_0.75'),
                (0.875, '09_soft_0.875'), (1.0, '10_soft_1.0')]),
    'med':    ('rig/renders/campaign3', 'rig/sets/campaign3 Project', 'sw100L',
               [(0.0, '01_neutral'), (0.125, '02_med_0.125'), (0.25, '03_med_0.25'),
                (0.375, '04_med_0.375'), (0.5, '05_med_0.5'), (0.625, '06_med_0.625'),
                (0.75, '07_med_0.75'), (0.875, '08_med_0.875'), (1.0, '09_med_1.0')]),
    'hard':   ('rig/renders/campaign3', 'rig/sets/campaign3 Project', 'sw100L',
               [(0.0, '01_neutral'), (0.125, '10_hard_0.125'), (0.25, '11_hard_0.25'),
                (0.375, '12_hard_0.375'), (0.5, '13_hard_0.5'), (0.625, '14_hard_0.625'),
                (0.75, '15_hard_0.75'), (0.875, '16_hard_0.875'), (1.0, '17_hard_1.0')]),
    'crunch': ('rig/renders/campaign3', 'rig/sets/campaign3 Project', 'sw100L',
               [(0.0, '01_neutral'), (0.25, '18_crunch_0.25'), (0.5, '19_crunch_0.5'),
                (0.75, '20_crunch_0.75'), (1.0, '21_crunch_1.0')]),
}
NB = 401


def curve(renders, project, segname, cell):
    probe_path, man = resolve_probe(renders, project)
    probe = read_wav(probe_path)['l']
    off = man['suite']['offsets']
    x = seg(probe, off, segname)
    w = read_wav(os.path.join(renders, os.path.basename(renders) + f' {cell}.wav'))['l']
    edges = np.linspace(-1, 1, NB + 1)
    cc = 0.5 * (edges[:-1] + edges[1:])
    best = None
    for L in range(LAG_LO, LAG_HI + 1):
        y = seg(w, off, segname, L)
        m = min(len(x), len(y))
        idx = np.clip(np.digitize(x[:m], edges) - 1, 0, NB - 1)
        cnt = np.bincount(idx, minlength=NB)
        sm = np.bincount(idx, weights=y[:m], minlength=NB)
        sq = np.bincount(idx, weights=y[:m] * y[:m], minlength=NB)
        ok = cnt > 30
        mean = np.zeros(NB); mean[ok] = sm[ok] / cnt[ok]
        sd = np.zeros(NB); sd[ok] = np.sqrt(np.maximum(sq[ok] / cnt[ok] - mean[ok] ** 2, 0))
        wd = float(np.mean(sd[ok] / (np.abs(mean[ok]) + 1e-3)))
        if best is None or wd < best[0]:
            best = (wd, L, mean.copy(), ok.copy())
    wd, L, mean, ok = best
    # fold the two halves together: the shapers are odd by measurement (§22)
    xs, ys = cc[ok], mean[ok]
    grid = np.linspace(0.0, 1.0, N)
    pos = np.interp(grid, xs[xs >= 0], ys[xs >= 0]) if (xs >= 0).sum() > 4 else np.zeros(N)
    negx, negy = -xs[xs <= 0][::-1], -ys[xs <= 0][::-1]
    neg = np.interp(grid, negx, negy) if len(negx) > 4 else pos
    out = 0.5 * (pos + neg)
    # An odd shaper must pass through the origin. The measured bin nearest zero
    # carries a small residual (~0.004), and left in the table it becomes a DC
    # OFFSET — silence in, DC out. Anchor the first sample and taper the
    # correction away over the first few samples so the slope near zero, which
    # is the small-signal gain, is preserved.
    if len(out):
        corr = out[0]
        taper = np.clip(1.0 - np.arange(len(out)) / 8.0, 0.0, 1.0)
        out = out - corr * taper
    return out, wd, L


def main():
    print('// GENERATED by tools/make_luts.py — do not edit by hand.')
    print('// Measured shaper curves for Bus Driver. Provenance and the reasoning')
    print('// for tables-not-formulas are in that script and in')
    print('// docs/reference/measurements.md sections 26, 35, 37, 39.')
    print('#pragma once\n')
    print(f'namespace drumbuss {{\nstatic constexpr int kShaperN = {N};\n')
    for fam, (R, P, segn, cells) in FAMILIES.items():
        drives, rows, widths = [], [], []
        for d, cell in cells:
            y, wd, L = curve(R, P, segn, cell)
            drives.append(d); rows.append(y); widths.append(wd)
            print(f'// {fam:6s} drive {d:<5} from {cell:<16s} lag {L}  width {wd:.3f}',
                  file=sys.stderr)
        print(f'// {fam}: {len(drives)} measured settings; per-bin width '
              f'{min(widths):.3f}..{max(widths):.3f}')
        print(f'static constexpr int k{fam.capitalize()}Steps = {len(drives)};')
        print(f'static constexpr float k{fam.capitalize()}Drive[] = {{'
              + ', '.join(f'{d:.4f}f' for d in drives) + '};')
        print(f'static constexpr float k{fam.capitalize()}Curve[][kShaperN] = {{')
        for d, y in zip(drives, rows):
            vals = ', '.join(f'{v:.6f}f' for v in y)
            print(f'  {{ {vals} }},   // drive {d}')
        print('};\n')
    print('}  // namespace drumbuss')


if __name__ == '__main__':
    main()
